routes/web.php
<?php

use App\Http\Controllers\AdController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LinkController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ShortLinkController;
use App\Http\Middleware\EnsureLinkIdExists;
use App\Models\User;
use App\Models\UserInfo;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// index
Route::get('/', [HomeController::class, 'index'])->name('home');

// login, logout
Route::get('/login', [LoginController::class, 'login'])->
        middleware('guest')->name('login');

Route::post('/authenticate', [LoginController::class, 'authenticate'])->
        middleware('guest')->name('authenticate');

Route::get('/logout', [LogoutController::class, 'logout'])->
        middleware('auth')->name('logout');

// link's CRUD
Route::resource('links', LinkController::class)
    ->middleware('auth');

Route::get('/{uuid}', [ShortLinkController::class, 'find']);


// fallback route
Route::fallback(function () {
    return redirect('/');
});

resources/views/index.blade.php
@extends('layout')

@section('content')

    <p>Link's list</p>

    <div class="row mb-3">
        {{ $links->links() }}
    </div>

    <div class="row">

        <div class="col">
            <a href="{{ route('links.create') }}" class="btn btn-success">New link</a>
        </div>

        <table class="table table-striped">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Full link</th>
                    <th scope="col">Short link</th>
                    <th scope="col">Clicks count</th>
                    <th scope="col">Manage</th>
                </tr>
            </thead>
            <tbody>

                    @forelse ($links as $key => $link)
                        <tr>
                            <th scope="row">{{ $key }}</th>
                            <td>{{ $link->link }}</td>
                            <td>{{ url('/' . $link->uuid) }}</td>
                            <td>{{ $link->clicks }}</td>
                            <td><a href="{{ route('links.show', ['link'=> $link->id]) }}" class="btn btn-info">Детали</a></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4">No links</td>
                        </tr>
                    @endforelse

            </tbody>
        </table>
    </div>

    <div class="row mb-3">
        {{ $links->links() }}
    </div>

@endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shortener</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>


<div class="container">

    @include('navbar')

</div>


<div class="container">

    @error('flash')
        <div class="alert alert-danger"> {{ $message }} </div>
    @enderror

    @if(session('flash'))
        <div class="alert alert-success"> {{ session('flash') }} </div>
    @endisset

    @yield('content')

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>



<?php

resources/views/linkForm.blade.php
@extends('layout')

@section('content')

    <p>Link form. {{ $description }}</p>

    <div class="row">

        <form action="{{ $route ?? route('links.store') }}" method="post">
            @csrf

            @if(!empty($method))
                <input name="_method" type="hidden" value="{{ $method }}">
            @endif

            @error('link')
            <hr>
            <div class="alert alert-danger"> {{ $message }} </div>
            @enderror
            <div class="mb-3">
                <label for="link" class="form-label">Link</label>
                <input type="url" class="form-control" id="link"
                       name="link" placeholder="http://example.com"
                       value="{{ old('link') ?? $link->link ?? '' }}">
            </div>

            <button type="submit" class="btn btn-success">{{ $button ?? 'Создать'}}</button>
        </form>
    </div>

@endsection

resources/views/linkView.blade.php
@extends('layout')

@section('content')

    <p>Link</p>

    <div class="row">

            <div class="col">
                <div class="card">
                    <div class="card-body">

                            <h5 class="card-title">Link id: {{ $link->id }}</h5>
                            <h5 class="card-text">Original link: {{ $link->link }}</h5>
                            <h5 class="card-text">Short link: {{ url('/' . $link->uuid) }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Clicks count: {{ $link->clicks }}</h6>

                        @can('update', $link)
                        <a href="{{ route('links.edit', ['link' => $link->id]) }}" class="btn btn-success">Редактировать</a>
                        @endcan
                        @can('delete', $link)
                            <form action="{{ route('links.destroy', ['link' => $link->id]) }}" method="post">
                                @csrf
                                <input name="_method" type="hidden" value="DELETE">
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        @endcan
                    </div>
                </div>
            </div>

    </div>

    <hr>
    <div class="row">
        <p>Статистика посещений</p>
        <div class="row mb-3">
            {{ $statistics->links() }}
        </div>

        <table class="table table-striped">
            <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">ip</th>
                <th scope="col">Country_code</th>
                <th scope="col">Country name</th>
                <th scope="col">City name</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
        @forelse ($statistics as $key => $statistic)
            <tr>
                <th scope="row">{{ $key }}</th>
                <td>{{ $statistic->ip }}</td>
                <td>{{ $statistic->country_code }}</td>
                <td>{{ $statistic->country_name }}</td>
                <td>{{ $statistic->city_name }}</td>
                <td>{{ $statistic->updated_at }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="6">No statistics</td>
            </tr>
        @endforelse
            </tbody>
        </table>

        <div class="row mb-3">
            {{ $statistics->links() }}
        </div>
    </div>

@endsection

resources/views/login.blade.php
@extends('layout')

@section('content')

    <p>Login</p>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('authenticate') }}" method="post">
        @csrf
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" name="remember" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Remember</label>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

@endsection

resources/views/navbar.blade.php
@section('navbar')

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Shortener</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ route('home') }}">Home</a>
                    </li>
                </ul>


                <ul class="d-flex flex-row mb-auto">

                    @guest()
                        <a class="btn btn-outline-success" href="/login">Login</a>
                    @endguest

                    @auth()
                            <a class="btn btn-outline-success" href="/logout">Logout</a>
                    @endauth

                </ul>
            </div>
        </div>
    </nav>

@show